### PR TITLE
removes unused jzlib dependency

### PR DESCRIPTION
**Pull request by santhosh-tekuri**

### CODE REVIEW

**Comment by Pacane** [comment]
So that dependency was there, but not used at all?

**Comment by kaendfinger** [comment]
I'm thinking that is still used by netty for compression when needed.

**Comment by santhosh-tekuri** [comment]
netty uses jdk zlib unless explicitly configured with system property

see https://github.com/afredlyj/learn-netty/blob/master/codec/src/main/java/io/netty/handler/codec/compression/ZlibCodecFactory.java

**Comment by a-hansen** [comment]
Added this to my current branch.

**Pull request closed without merging**
